src/Entity/ProductsPromotions.php
<?php

namespace App\Entity;

use App\Repository\ProductsPromotionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsPromotionsRepository::class)]
class ProductsPromotions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column]
    private ?int $discount = null;

    #[ORM\OneToMany(mappedBy: 'productsPromotions', targetEntity: Products::class)]
    private Collection $products;

    #[ORM\OneToMany(mappedBy: 'productspromotions', targetEntity: Categories::class)]
    private Collection $categories;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    public function setDiscount(int $discount): static
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * @return Collection<int, Products>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setProductsPromotions($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getProductsPromotions() === $this) {
                $product->setProductsPromotions(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->setProductspromotions($this);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getProductspromotions() === $this) {
                $category->setProductspromotions(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/Admin/MainController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin', name: 'admin_')]
class MainController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->render('admin/index.html.twig');
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\CategoriesRepository;
use App\Repository\ProductsPromotionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'main')]
    public function index(CategoriesRepository $categoriesRepository, ProductsPromotionsRepository $productsPromotionsRepository): Response
    {

        return $this->render('main/index.html.twig', [
            'categories' => $categoriesRepository->findBy([], 
            ['categoryOrder' => "asc"]),
            'productspromotions' => $productsPromotionsRepository->findAll()
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}
	<main class="container my-5">
		<section class="row">
			<div class="col-12 text-center">
				<h1>Gaming.shop</h1>
				<h3>Bienvenue dans le monde du gaming</h3>
			</div>

			{% for productspromotion in productspromotions %}
				{% if productspromotion|length > 0 %}

					<div class="col-8 mt-5 mx-auto">
						<div class="card mb-3 bg-dark text-light" style="max-width: 800px;">
						<div class="row g-0">
							<div class="col-md-4">
								<img src="{{ asset('assets/uploads/promotions/promo1.jpg')}}" class="img-fluid rounded-start" alt="...">
							</div>
							<div class="col-md-8">
								<div class="card-body">
									<h5 class="card-title">{{productspromotion.name}}</h5>
									<p class="card-text">{{productspromotion.description}}</p>
									<p class="card-text">
										<small class="text-body-light">Du
									{{ productspromotion.startDate ? productspromotion.startDate|date('Y-m-d') : '' }}
									au
									{{ productspromotion.endDate ? productspromotion.endDate|date('Y-m-d') : '' }}</small>
									</p>
								</div>
							</div>
						</div>
					</div>
					</div>
					

				{% endif %}
			{% endfor %}

			{% for category in categories %}
				{% if category.parent == null %}
					<div class="col-12 mt-5">
						<h2>{{ category.name }}</h2>
					</div>
				{% else %}
					<div class="col-lg-3 col-md-6 col-12 my-5">
						<div class="card h-100 box-reflect">
							<div class="card-body">
								<h3 class="card-title">{{ category.name }}</h3>
								<a href=" {{ path('categories_list', {slug: category.slug}) }} " class="btn btn-dark">Voir les produits</a>
							</div>
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</section>
	</main>
{% endblock %}